/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlyshopdocaulong;

/**
 *
 * @author Laptop
 */
public class Dangkytaikhoan extends javax.swing.JFrame {

    /**
     * Creates new form Dangkytaikhoan
     */
    public Dangkytaikhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_tendangnhap = new javax.swing.JTextField();
        tendangnhap = new javax.swing.JLabel();
        matkhau = new javax.swing.JLabel();
        txt_matkhau = new javax.swing.JTextField();
        btn_dangky = new javax.swing.JButton();
        tendangnhap1 = new javax.swing.JLabel();
        matkhau1 = new javax.swing.JLabel();
        txt_matkhau1 = new javax.swing.JTextField();
        matkhau2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        matkhau3 = new javax.swing.JLabel();
        txt_matkhau2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tendangnhap.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txt_tendangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tendangnhapActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tendangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 240, 40));

        tendangnhap.setBackground(new java.awt.Color(51, 204, 255));
        tendangnhap.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tendangnhap.setForeground(new java.awt.Color(255, 255, 255));
        tendangnhap.setText("Đăng kí tài khoản");
        getContentPane().add(tendangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        matkhau.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        matkhau.setForeground(new java.awt.Color(255, 255, 255));
        matkhau.setText("Mật khẩu :");
        getContentPane().add(matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        txt_matkhau.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txt_matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matkhauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 240, 40));

        btn_dangky.setBackground(new java.awt.Color(102, 204, 255));
        btn_dangky.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btn_dangky.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangky.setText("Đăng ký");
        btn_dangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangkyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangky, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 130, 40));

        tendangnhap1.setBackground(new java.awt.Color(51, 204, 255));
        tendangnhap1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tendangnhap1.setForeground(new java.awt.Color(255, 255, 255));
        tendangnhap1.setText("Tên đăng nhập :");
        getContentPane().add(tendangnhap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        matkhau1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        matkhau1.setForeground(new java.awt.Color(255, 255, 255));
        matkhau1.setText("Xác nhận mật khẩu:");
        getContentPane().add(matkhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        txt_matkhau1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txt_matkhau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matkhau1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_matkhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 240, 40));

        matkhau2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        matkhau2.setForeground(new java.awt.Color(255, 255, 255));
        matkhau2.setText("Câu hỏi:");
        getContentPane().add(matkhau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 240, 40));

        matkhau3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        matkhau3.setForeground(new java.awt.Color(255, 255, 255));
        matkhau3.setText("Nhập câu trả lời:");
        getContentPane().add(matkhau3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        txt_matkhau2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txt_matkhau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matkhau2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_matkhau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 240, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BODUA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tendangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tendangnhapActionPerformed
        // TODO add your handling code here:
        String tendangnhap = txt_tendangnhap.getText();
        System.out.println("Họ tên: "+ tendangnhap);
    }//GEN-LAST:event_txt_tendangnhapActionPerformed

    private void txt_matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matkhauActionPerformed
        // TODO add your handling code here:
        String matkhau = txt_matkhau.getText();
        System.out.println("Họ tên: "+ matkhau);
    }//GEN-LAST:event_txt_matkhauActionPerformed

    private void btn_dangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangkyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangkyActionPerformed

    private void txt_matkhau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matkhau1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matkhau1ActionPerformed

    private void txt_matkhau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matkhau2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matkhau2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dangkytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dangkytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dangkytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dangkytaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dangkytaikhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangky;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel matkhau;
    private javax.swing.JLabel matkhau1;
    private javax.swing.JLabel matkhau2;
    private javax.swing.JLabel matkhau3;
    private javax.swing.JLabel tendangnhap;
    private javax.swing.JLabel tendangnhap1;
    private javax.swing.JTextField txt_matkhau;
    private javax.swing.JTextField txt_matkhau1;
    private javax.swing.JTextField txt_matkhau2;
    private javax.swing.JTextField txt_tendangnhap;
    // End of variables declaration//GEN-END:variables
}
